#!/bin/bash

load_config() {
	echo "Load tunnel.conf"
	. $SNAP_DATA/tunnel/tunnel.conf
}

config_checksum() {
	echo -n $(sha256sum $SNAP_DATA/tunnel/tunnel.conf | awk '{ print $1 }')
	echo -n $SNAP_REVISION
}

tinc_name() {
	hostname | sed 's/[^a-z0-9]//'
}

# I got DENIED by apparmor when I tried to place this logic in the
# configure hook, and yes I added the needed plugs.
reconfigure() {
	if [ x$BRIDGE != x ]; then
		if brctl show $BRIDGE 2>&1 | grep -q "No such device"; then
			echo "Setup a new bridge called $BRIDGE"
			brctl addbr $BRIDGE
			brctl stp $BRIDGE on
		else
			echo "Reuse existing bridge $BRIDGE"
			echo "It's recommended to enable stp on this bridge"
		fi
	fi

	if [ ! -f $SNAP_DATA/tinc/rsa_key.priv ]; then
		echo -e "\n\n\n\n" | $SNAP/sbin/tinc -c $SNAP_DATA/tinc generate-keys 4096

		# If tinc choosed another name, rename it.
		if [ x$(ls -1 $SNAP_DATA/tinc/hosts/ | wc -l) == x1 ]; then
			mv $SNAP_DATA/tinc/hosts/* $SNAP_DATA/tinc/hosts/$(tinc_name)
		fi
	fi

	touch $SNAP_DATA/tunnel/tinc-is-configured
}

while [ -f $SNAP_DATA/tunnel/interfaces_needed ]; do
	if brctl addbr testbrin99; then
		rm $SNAP_DATA/tunnel/interfaces_needed
		brctl delbr testbrin99
	fi
	sleep 10
done

while sleep 10; do
	if [ -f $SNAP_DATA/tunnel/tunnel.conf ]; then
		if [[ $CONFIG_CHECKSUM != $(config_checksum) ]]; then
			echo "Config checksum changed from $CONFIG_CHECKSUM to $(config_checksum), reload config."
			load_config
			reconfigure
			CONFIG_CHECKSUM=$(config_checksum)
		fi
	fi

	if [ ! -e $SNAP_DATA/tinc/pid ]; then
		echo "Unable to detect tinc pidfile, restart tincd service in 5 seconds"
		sleep 5
		snapctl restart tunnel.tinc
	fi
done
