#!/bin/bash

echo snap connect tunnel:network-control
echo snap connect tunnel:network-setup-control
echo snap connect tunnel:network-observe
echo snap set tunnel ip4addr= # run configure hook to detect IP
