#!/bin/bash
exec > >(tee "$SNAP_DATA/logs/install.log") 2>&1

mkdir -p $SNAP_DATA/logs
mkdir -p $SNAP_DATA/tinc
mkdir -p $SNAP_DATA/tinc/hosts
mkdir -p $SNAP_DATA/tunnel
mkdir -p $SNAP_DATA/tmp

# This file will be removed by the service when the user has
# connected the needed interfaces.
touch $SNAP_DATA/tunnel/interfaces_needed
